version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: t2kmcg-dev
    container_name: t2kmcg-dev
    tty: true
    working_dir: /go/src/github.com/yuta1402/t2kmcg
    volumes:
      - ./:/go/src/github.com/yuta1402/t2kmcg
